language: node_js
node_js:
  - "9.11.1"
dist: trusty
sudo: false

branches:
  only:
  - master
  - gh-pages
  

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn 

script:
  - yarn minimal-build

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: packages/personal-blog-minimal/public
  on:
    branch: gh-pages